export const FRUITS = [
    {
      id: 0,
      name: "Tangerine",
      slug: "tangerine",
      src: "/tangerine.png",
      desc: "Tangerines chote citrus fruits hote hain jo dikhne mein oranges jaise lagte hain, lekin wo chote hote hain aur unka skin patla aur easily peel hone wala hota hai. Ye typically sweet hote hain, thodi si tart flavor ke saath, aur aksar oranges se zyada juicy hote hain. Tangerines ki ek alag khushbu hoti hai aur inka rang bright orange hota hai.",
      price: "2.0",
      family: "Citrus",
      colors: ["Orange"],
      vitamins: ["C"],
    },
    {
      id: 1,
      name: "Melon",
      slug: "melon",
      src: "/melon.png",
      desc: "Melon ek broad term hai jo Gourd family ke various fruits ko refer karta hai, jismein cantaloupe, honeydew, aur watermelon shamil hain. Melons ki pehchan unke sweet, juicy flesh aur refreshing taste se hoti hai. Cantaloupes ka flavor sweet aur thoda musky hota hai, honeydews typically zyada sweet hote hain aur unme subtle honey-jaisa taste hota hai, aur watermelons ka texture crisp hota hai aur unka flavor bahut sweet hota hai, jisme thodi si freshness ki jhalak hoti hai.",
      price: "3.5",
      family: "Gourd",
      colors: ["Green"],
      vitamins: ["A", "C"],
    },
    {
      id: 2,
      name: "Watermelon",
      slug: "watermelon",
      src: "/watermelon.png",
      desc: "Watermelon ek bada, gol fruit hota hai jiska thick green rind hota hai aur juicy, red flesh hota hai jisme black seeds hote hain (halaanki seedless varieties bhi common hain). Watermelons mein paani ki matra bahut zyada hoti hai, jo unhe bahut hydrating aur refreshing banata hai. Unka flavor sweet aur thoda tangy hota hai, aur unka texture crisp hota hai.",
      price: "6.0",
      family: "Gourd",
      colors: ["Red", "Green"],
      vitamins: ["A", "C"],
    },
    {
      id: 3,
      name: "Lemon",
      slug: "lemon",
      src: "/lemon.png",
      desc: "Lemons chote, peele citrus fruits hote hain jinme bright, acidic flavor hota hai. Unka taste tart hota hai jo fruit ki ripeness ke hisaab se mildly sour se lekar intensely puckering tak ho sakta hai. Lemons ka istemal commonly dishes, beverages, aur desserts mein acidity aur freshness add karne ke liye kiya jata hai.",
      price: "1.5",
      family: "Citrus",
      colors: ["Yellow"],
      vitamins: ["C"],
    },
    {
      id: 4,
      name: "Banana",
      slug: "banana",
      src: "/banana.png",
      desc: "Bananas lambe, curved fruits hote hain jinki thick, yellow skin hoti hai jo easily peel ho jati hai aur andar soft, creamy flesh hota hai. Unka flavor sweet hota hai jisme vanilla ki subtle notes hoti hain aur unka texture creamy hota hai. Bananas natural sugars se bharpur hote hain, jo unhe snacking, baking, aur smoothies mein blend karne ke liye ek popular choice banata hai.",
      price: "5.0",
      family: "Other",
      colors: ["Yellow"],
      vitamins: ["B6"],
    },
    {
      id: 5,
      name: "Pineapple",
      slug: "pineapple",
      src: "/pineapple.png",
      desc: "Pineapples tropical fruits hote hain jinki pehchan unke spiky, rough skin aur sweet, juicy flesh se hoti hai. Unka rang vibrant yellow hota hai aur unka flavor distinctively sweet aur tangy hota hai jisme tropical notes ki jhalak hoti hai. Pineapples ko fresh khaya ja sakta hai, juice banaya ja sakta hai, grill kiya ja sakta hai, ya phir sweet aur savory dono tarah ki dishes mein use kiya ja sakta hai.",
      price: "3.0",
      family: "Other",
      colors: ["Yellow", "Green"],
      vitamins: ["C", "B6"],
    },
    {
      id: 6,
      name: "Mango",
      slug: "mango",
      src: "/mango.png",
      desc: "Mangos tropical fruits hote hain jinki smooth, golden-yellow skin hoti hai aur juicy, sweet flesh hota hai jo ek bade, flat seed ke aas-paas hota hai. Unka texture rich aur creamy hota hai aur unka flavor profile complex hota hai jisme sweetness, tanginess aur tropical flavors jaise peach, pineapple, aur citrus ke hints milte hain. Mangos ko aksar fresh khaya jata hai ya phir smoothies, salads, salsas, aur desserts mein use kiya jata hai.",
      price: "5.0",
      family: "Cashew",
      colors: ["Yellow", "Red", "Green"],
      vitamins: ["A", "C"],
    },
    {
      id: 7,
      name: "Red Apple",
      slug: "red-apple",
      src: "/red-apple.png",
      desc: "Red apples apples ki sabse common varieties mein se ek hain. Unka chamakdar laal skin hota hai aur crisp, juicy flesh hota hai. Red apples ka flavor profile typically balanced hota hai, jismein sweetness ke saath thodi si tartness bhi hoti hai. Ye versatile hote hain aur inhe fresh khaya ja sakta hai, cooking mein use kiya ja sakta hai, ya phir juice mein press kiya ja sakta hai.",
      price: "1.3",
      family: "Rose",
      colors: ["Red"],
      vitamins: ["C"],
    },
    {
      id: 8,
      name: "Green Apple",
      slug: "green-apple",
      src: "/green-apple.png",
      desc: "Green apples, jinhe Granny Smith apples bhi kaha jata hai, ka bright green skin hota hai aur unka flavor tart aur tangy hota hai. Ye apne crisp texture aur refreshing taste ke liye jaane jaate hain. Green apples ka istemal aksar baking, salads, aur sauces mein kiya jata hai, kyunki unki tartness sweeter ingredients ke saath ek acha contrast create karti hai.",
      price: "1.5",
      family: "Rose",
      colors: ["Green"],
      vitamins: ["C"],
    },
    {
      id: 9,
      name: "Pear",
      slug: "pear",
      src: "/pear.png",
      desc: "Pears sweet aur juicy fruits hote hain jinki ek distinctive ghanti-jaisi shape hoti hai aur smooth skin hota hai jo green se lekar yellow aur red tak ke rang ka ho sakta hai. Unka flavor delicate aur floral hota hai, jisme thodi sweetness aur subtle grainy texture hoti hai. Pears ko fresh khaya ja sakta hai ya phir desserts, salads, aur savory dishes mein use kiya ja sakta hai.",
      price: "2.5",
      family: "Rose",
      colors: ["Green"],
      vitamins: ["C", "K"],
    },
    {
      id: 10,
      name: "Peach",
      slug: "peach",
      src: "/peach.png",
      desc: "Peaches soft, fuzzy fruits hote hain jinke andar sweet aur juicy flesh hota hai jo yellow se orange tak ke rang ka ho sakta hai. Unka flavor rich aur aromatic hota hai jisme floral aur tropical notes ki jhalak hoti hai. Peaches ko aam taur par fresh khaya jata hai ya phir desserts jaise pies, cobblers, aur preserves mein use kiya jata hai.",
      price: "3.0",
      family: "Rose",
      colors: ["Orange"],
      vitamins: ["A", "C"],
    },
    {
      id: 11,
      name: "Cherries",
      slug: "cherries",
      src: "/cherries.png",
      desc: "Cherries chote, gol fruits hote hain jinki chamakdar skin bright red se lekar deep purple tak ke rang ki ho sakti hai. Unka flavor sweet aur tangy hota hai jisme thodi si tartness bhi hoti hai. Cherries ko aam taur par fresh snack ke roop mein khaya jata hai ya phir desserts, jams, aur beverages mein use kiya jata hai.",
      price: "4.0",
      family: "Rose",
      colors: ["Red", "Green"],
      vitamins: ["C"],
    },
    {
      id: 12,
      name: "Strawberry",
      slug: "strawberry",
      src: "/strawberry.png",
      desc: "Strawberries dil ke shape ke fruits hote hain jinka rang bright red hota hai aur unki surface par chote seeds hote hain. Unka flavor sweet aur thoda tart hota hai, aur unka flesh juicy aur fragrant hota hai. Strawberries apne delicious taste aur vibrant color ki wajah se desserts, salads, smoothies, aur jams mein bahut popular hain.",
      price: "2.8",
      family: "Rose",
      colors: ["Red"],
      vitamins: ["C"],
    },
    {
      id: 13,
      name: "Blueberries",
      slug: "blueberries",
      src: "/blueberries.png",
      desc: "Blueberries chote, gol berries hote hain jinka rang deep blue-purple hota hai aur unpar thoda sa waxy coating hota hai. Unka flavor sweet aur mildly tart hota hai aur unka flesh juicy hota hai. Blueberries antioxidants se bharpur hote hain aur inhe aksar fresh snack ke roop mein khaya jata hai ya phir cereals, muffins, pancakes, aur desserts mein add kiya jata hai.",
      price: "4.5",
      family: "Berry",
      colors: ["Blue", "Black"],
      vitamins: ["C", "K"],
    },
    {
      id: 14,
      name: "Grapes",
      slug: "grapes",
      src: "/grapes.png",
      desc: "Grapes chote, gol ya oval shape ke fruits hote hain jo vines par clusters mein ugte hain. Ye green, red, aur purple jaise various colors mein aate hain. Grapes ka flesh sweet aur juicy hota hai jisme thodi si tartness hoti hai, aur unka flavor variety ke hisaab se alag-alag ho sakta hai. Inhe commonly fresh snack ke roop mein khaya jata hai, salads mein use kiya jata hai, ya phir juices, wines, aur raisins mein process kiya jata hai.",
      price: "3.0",
      family: "Berry",
      colors: ["Purple"],
      vitamins: ["C", "K"],
    },
    {
      id: 15,
      name: "Kiwi",
      slug: "kiwi",
      src: "/kiwi.png",
      desc: "Kiwi, jise kiwifruit ya Chinese gooseberry bhi kaha jata hai, ek chota, oval shape ka fruit hota hai jiska skin brown aur fuzzy hota hai aur andar ka flesh vibrant green hota hai jisme chote-chote black seeds hote hain. Kiwi ka flavor sweet aur tangy hota hai jisme tropical notes hote hain jo strawberries aur melons ki yaad dilate hain. Ise commonly fresh khaya jata hai, slice karke khaya jata hai, ya phir fruit salads, smoothies, aur desserts mein use kiya jata hai.",
      price: "1.0",
      family: "Other",
      colors: ["Green", "Brown"],
      vitamins: ["C", "K"],
    },
    {
      id: 16,
      name: "Tomato",
      slug: "tomato",
      src: "/tomato.png",
      desc: "Halaanki aam taur par ise vegetable samjha jata hai, technically tomatoes fruits hote hain. Ye various colors mein aate hain, jaise red, yellow, orange, aur yahan tak ki purple bhi, aur unka skin smooth aur shiny hota hai. Tomatoes ka flavor mildly sweet aur tangy hota hai, unka flesh juicy hota hai aur taste mein thoda acidic hota hai. Ye versatile hote hain aur inhe salads, sauces, soups, sandwiches, aur bahut saare other dishes mein use kiya jata hai.",
      price: "1.5",
      family: "Nightshade",
      colors: ["Red"],
      vitamins: ["A", "C"],
    },
    {
      id: 17,
      name: "Olive",
      slug: "olive",
      src: "/olive.png",
      desc: "Olives chote, oval shape ke fruits hote hain jinki smooth skin hoti hai jo ripeness aur variety ke hisaab se green se lekar black tak ke rang ki ho sakti hai. Unka flavor rich aur salty hota hai aur unka texture unique buttery hota hai. Olives ko aksar khane se pehle brine ya cure kiya jata hai aur inhe commonly Mediterranean cuisine, salads, pizzas mein use kiya jata hai aur garnish ke roop mein bhi istemal kiya jata hai.",
      price: "4.0",
      family: "Other",
      colors: ["Green"],
      vitamins: ["E", "K"],
    },
    {
      id: 18,
      name: "Coconut",
      slug: "coconut",
      src: "/coconut.png",
      desc: "Coconuts bade, brown fruits hote hain jinke upar hard, hairy shell hota hai aur andar sweet, white flesh hota hai. Unka flavor tropical aur thoda sweet hota hai aur unka texture rich aur creamy hota hai. Coconuts ko various forms mein use kiya jata hai, jaise fresh coconut water, coconut milk, shredded coconut, aur coconut oil. Ye bahut saare tropical dishes aur desserts mein ek staple ingredient hote hain.",
      price: "2.8",
      family: "Palm",
      colors: ["Brown"],
      vitamins: ["B6"],
    },
    {
      id: 19,
      name: "Avocado",
      slug: "avocado",
      src: "/avocado.png",
      desc: "Avocado ek pear-shape ka fruit hota hai jiska skin dark green ya blackish hota hai aur uska creamy, pale green flesh ek bade seed ke aas-paas hota hai. Avocados ka texture buttery hota hai aur unka flavor mild aur nutty hota hai jisme sweetness aur earthiness ki jhalak hoti hai. Inhe aksar unke creamy texture aur rich flavor ki wajah se salads, sandwiches, guacamole, aur smoothies mein fresh khaya jata hai.",
      price: "3.0",
      family: "Laurel",
      colors: ["Green", "Brown"],
      vitamins: ["K", "E"],
    },
    {
      id: 20,
      name: "Eggplant",
      slug: "eggplant",
      src: "/eggplant.png",
      desc: "Eggplant, jise aubergine bhi kaha jata hai, ek bada, ande ke shape ka fruit hota hai jiska smooth, shiny skin deep purple se lekar white tak ke rang ka ho sakta hai. Eggplants ka flavor mild aur thoda bitter hota hai aur cook karne par unka texture spongy ho jata hai. Inhe commonly various cuisines mein use kiya jata hai, jaise Mediterranean aur Asian, aur inhe grill, roast, fry ya stew kiya ja sakta hai dishes jaise ratatouille, moussaka, aur curries mein.",
      price: "1.8",
      family: "Nightshade",
      colors: ["Purple"],
      vitamins: ["K"],
    },
    {
      id: 21,
      name: "Cucumber",
      slug: "cucumber",
      src: "/cucumber.png",
      desc: "Cucumber ek cylindrical fruit hota hai jiska smooth, dark green skin hota hai aur crisp, watery flesh hota hai. Iska flavor mild aur refreshing hota hai jisme subtle sweetness ke hints hote hain aur peel mein thodi si bitterness hoti hai. Cucumbers ko commonly raw khaya jata hai salads, sandwiches mein, aur ek crunchy snack ke roop mein. Inhe pickles banane ke liye bhi use kiya jata hai aur ye chilled soups jaise gazpacho mein ek popular ingredient hote hain.",
      price: "1.0",
      family: "Gourd",
      colors: ["Green"],
      vitamins: ["K"],
    },
    {
      id: 22,
      name: "Bell Pepper",
      slug: "bell-pepper",
      src: "/bell-pepper.png",
      desc: "Bell peppers bade, ghanti ke shape ke fruits hote hain jinki glossy, smooth skin hoti hai jo various colors mein aati hai, jaise green, red, yellow, aur orange. Unka texture crisp hota hai aur flavor sweet aur thoda tangy hota hai. Bell peppers versatile hote hain aur inhe raw khaya ja sakta hai salads mein, ya phir stuffed, roasted, grilled, ya sautéed kiya ja sakta hai various dishes mein jaise stir-fries, fajitas, aur pasta sauces.",
      price: "1.3",
      family: "Nightshade",
      colors: ["Green"],
      vitamins: ["A", "C"],
    },
    {
      id: 23,
      name: "Hot Pepper",
      slug: "hot-pepper",
      src: "/hot-pepper.png",
      desc: "Hot peppers, jinhe chili peppers ya chilies bhi kaha jata hai, wide range ke shapes, sizes, colors, aur spiciness levels mein aate hain. Inme capsaicin hota hai, jo ek compound hai jo inki heat ke liye responsible hai. Hot peppers ke flavors mildly sweet se lekar intensely spicy tak ho sakte hain, variety ke hisaab se. Inhe commonly dishes, sauces, salsas, aur marinades mein heat aur flavor add karne ke liye use kiya jata hai.",
      price: "2.5",
      family: "Nightshade",
      colors: ["Red"],
      vitamins: ["C"],
    },
    {
      id: 24,
      name: "Pumpkin",
      slug: "pumpkin",
      src: "/pumpkin.png",
      desc: "Pumpkin ek bada, gol fruit hota hai jiska thick, orange ya yellowish skin hota hai aur sweet, fibrous flesh hota hai. Iska flavor mild aur earthy hota hai jisme subtle sweetness ke hints hote hain, jo ise both sweet aur savory dishes ke liye versatile banata hai. Pumpkins ko commonly pies, soups, stews, curries, aur baked goods jaise muffins aur bread mein use kiya jata hai. Iske alawa, pumpkin seeds ko roast karke snack ke roop mein khaya ja sakta hai ya garnish ke liye use kiya ja sakta hai.",
      price: "2.5",
      family: "Gourd",
      colors: ["Orange", "Yellow"],
      vitamins: ["A"],
    },
  ];
  
  export const COLOROPTIONS = [
    "Purple",
    "Green",
    "Brown",
    "Red",
    "Orange",
    "Yellow",
    "Blue",
    "Black",
  ];
  export const FAMILYOPTIONS = [
    { label: "Rose", value: "Rose" },
    { label: "Citrus", value: "Citrus" },
    { label: "Nightshade", value: "Nightshade" },
    { label: "Gourd", value: "Gourd" },
    { label: "Palm", value: "Palm" },
    { label: "Cashew", value: "Cashew" },
    { label: "Berry", value: "Berry" },
    { label: "Laurel", value: "Laurel" },
    { label: "Other", value: "Other" },
  ];
  export const VITAMINSOPTIONS = [
    { label: "Vitamin C", value: "C" },
    { label: "Vitamin A", value: "A" },
    { label: "Vitamin K", value: "K" },
    { label: "Vitamin E", value: "E" },
    { label: "Vitamin B6", value: "B6" },
  ];